---

stages:
  - Build
  - Deploy

Build:
  stage: Build
  image:
    name: gcr.io/kaniko-project/executor:v1.17.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  tags:
   - k8s
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      changes:
        - Dockerfile
        - src/**/*

Deploy:
  stage: Deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config use-context ${KUBE_CONTEXT}
    - |
      echo "Replace Secret Variables"
      (echo "cat <<EOF"; cat k8s/secrets.yaml; echo EOF) | sh > k8s/tmp_secrets.yaml && mv k8s/tmp_secrets.yaml k8s/secrets.yaml
    - |
      echo "Check ns ${NAMESPACE}..."
      kubectl get ns ${NAMESPACE} 2> /dev/null || kubectl create ns ${NAMESPACE}
    - |
      echo "Deploy on k8s..."
      kubectl apply -f k8s
  tags:
    - k8s
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  environment:
    name: production
    url: $PROD_URL
