---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
  namespace: go-training
  labels:
    app: go-webserver
spec:
  selector:
    matchLabels:
      app: go-webserver
  replicas: 3
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
        - name: go-webserver
          image: cr.gitlab.ninux.org/ingmg/go-training:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-imdb-app
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-imdb-app
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-imdb-app
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-imdb-app
                  key: dbname
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: pg-cluster-imdb-app
                  key: port
            - name: DB_SSL_MODE
              value: disable
            - name: DB_TIMEZONE
              value: Europe/Amsterdam
          ports:
            - containerPort: 8080
              name: go-webserver
      imagePullSecrets:
        - name: docker-registry-secret
