---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webserver
  namespace: go-training
  labels:
    app: go-webserver
spec:
  selector:
    matchLabels:
      app: go-webserver
  replicas: 3
  template:
    metadata:
      labels:
        app: go-webserver
    spec:
      containers:
        - name: go-webserver
          image: cr.gitlab.ninux.org/ingmg/go-training:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort: 8080
              name: go-webserver
      imagePullSecrets:
        - name: docker-registry-secret
