---

apiVersion: v1
kind: Service
metadata:
  name: go-webserver
  namespace: go-training
spec:
  type: LoadBalancer
  selector:
    app: go-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: go-webserver
